@startuml

entity blocks {
  id: BIGINT <<PK>>
  --
  height: BIGINT
  time: DATETIME
  created_at: DATETIME
  updated_at: DATETIME
}

entity transactions {
  id: BIGINT <<PK>>
  --
  block_id: BIGINT <<index>>
  hash: VARCHAR(191)
  raw_log: TEXT
  created_at: DATETIME
  updated_at: DATETIME
}

entity identifiers {
  id: BIGINT <<PK>>
  --
  identifier: VARCHAR(191)
  created_at: DATETIME
  updated_at: DATETIME
}

entity change_controller_messages {
  id: BIGINT <<PK>>
  --
  transaction_id: BIGINT <<index>>
  identifier_id: BIGINT <<index>>
  new_controller: VARCHAR(191)
  created_at: DATETIME
  updated_at: DATETIME
}

entity set_attribute_messages {
  id: BIGINT <<PK>>
  --
  transaction_id: BIGINT <<index>>
  identifier_id: BIGINT <<index>>
  key: TEXT
  value: TEXT
  validity: BIGINT
  created_at: DATETIME
  updated_at: DATETIME
}

entity revoke_attribute_messages {
  id: BIGINT <<PK>>
  --
  transaction_id: BIGINT <<index>>
  identifier_id: BIGINT <<index>>
  name: TEXT
  value: TEXT
  created_at: DATETIME
  updated_at: DATETIME
}

entity controllers { 
  id: BIGINT <<PK>>
  --
  identifier_id: BIGINT <<index>>
  version: BIGINT
  controller: VARCHAR(191)
  created_at: DATETIME
  updated_at: DATETIME
}

entity documents {
  id: BIGINT <<PK>>
  --
  identifier_id: BIGINT <<index>>
  version: BIGINT
  content: TEXT
  created_at: DATETIME
  updated_at: DATETIME
}

blocks ||---o{ transactions
transactions ||---o{ change_controller_messages
transactions ||---o{ set_attribute_messages
transactions ||---o{ revoke_attribute_messages

identifiers ||---o{ change_controller_messages
identifiers ||---o{ set_attribute_messages
identifiers ||---o{ revoke_attribute_messages

identifiers ||---o{ controllers
identifiers ||---o{ documents

@enduml