@startuml

entity blocks {
  id: BIGINT <<PK>>
  --
  block_number: BIGINT
  created_at: DATETIME
  updated_at: DATETIME
}

entity transactions {
  id: BIGINT <<PK>>
  --
  block_id: BIGINT <<index>>
  transaction_hash: VARCHAR(191)
  from_address: VARCHAR(191)
  raw_log: TEXT
  created_at: DATETIME
  updated_at: DATETIME
}

entity method_specific_strings {
  id: BIGINT <<PK>>
  --
  address: VARCHAR(191)
  created_at: DATETIME
  updated_at: DATETIME
}

entity change_controller_messages {
  id: BIGINT <<PK>>
  --
  transaction_id: BIGINT <<index>>
  method_specific_string_id: BIGINT <<index>>
  old_controller: VARCHAR(191)
  new_controller: VARCHAR(191)
  created_at: DATETIME
  updated_at: DATETIME
}

entity set_attribute_messages {
  id: BIGINT <<PK>>
  --
  transaction_id: BIGINT <<index>>
  method_specific_string_id: BIGINT <<index>>
  key: TEXT
  value: TEXT
  created_at: DATETIME
  updated_at: DATETIME
}

entity revoke_attribute_messages {
  id: BIGINT <<PK>>
  --
  transaction_id: BIGINT <<index>>
  method_specific_string_id: BIGINT <<index>>
  created_at: DATETIME
  updated_at: DATETIME
}

entity controllers { 
  id: INTEGER <<PK>>
  --
  method_specific_string_id: BIGINT <<index>>
  version_id: BIGINT <<index>>
  address: VARCHAR(191)
  created_at: DATETIME
  updated_at: DATETIME
}

entity attributes {
  id: BIGINT <<PK>>
  --
  method_specific_string_id: BIGINT <<index>>
  version_id: BIGINT <<index>>
  key: TEXT
  value: TEXT
  created_at: DATETIME
  updated_at: DATETIME
}

entity attribute_validities {
  id: BIGINT <<PK>>
  --
  attribute_id: BIGINT <<index>>
  version_id: BIGINT <<index>>
  valid_to: DATETIME
  created_at: DATETIME
  updated_at: DATETIME
}

blocks ||---o{ transactions
transactions ||---o{ change_controller_messages
transactions ||---o{ set_attribute_messages
transactions ||---o{ revoke_attribute_messages

method_specific_strings ||---o{ change_controller_messages
method_specific_strings ||---o{ set_attribute_messages
method_specific_strings ||---o{ revoke_attribute_messages

method_specific_strings ||---o{ controllers
method_specific_strings ||---o{ attributes
attributes ||---o{ attribute_validities

@enduml